[package]
name = "particles_6_3"
version = "0.1.0"
authors = ["iThinkyouknow <woontlt.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.73"
piston2d-graphics = "0.23"
rand = "0.3"
