[package]
name = "chip_8_cpu_multi_adder_5_5"
version = "0.1.0"
authors = ["iThinkyouknow <woontlt.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
